name = "tts-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
API_KEY = "abc"

[dev]
ip = "0.0.0.0"
port = 8787

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1
